import { StyleSheet, Platform, StatusBar } from 'react-native';

export const styles = StyleSheet.create({
  // Main container styles
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  scene: {
    flex: 1,
  },
  tabBar: {
    backgroundColor: '#fff',
    elevation: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  tabLabel: {
    fontFamily: 'Outfit-Medium',
    fontSize: 14,
    textTransform: 'capitalize',
  },
  tabIndicator: {
    backgroundColor: '#2667ff',
    height: 3,
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingVertical: 12,
    paddingBottom: Platform.OS === 'ios' ? 30 : 12,
  },
  navItem: {
    alignItems: 'center',
    flex: 1,
  },
  navLabel: {
    fontSize: 12,
    marginTop: 4,
    fontFamily: 'Outfit-Regular',
    color: '#b0b0b0',
  },
  navPlusWrapper: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#2667ff',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -30,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  navPlusButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#2667ff',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#fff',
  },
  // Account Section Styles
  accountContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  // Profile Header
  coverPhotoContainer: {
    width: '100%',
    position: 'relative',
  },
  profileHeader: {
    marginBottom: 20,
  },
  coverPhoto: {
    width: '100%',
    height: 150,
    backgroundColor: '#f5f8fa',
  },
  coverPhotoPlaceholder: {
    width: '100%',
    height: 150,
    backgroundColor: '#2667ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profilePicContainer: {
    position: 'absolute',
    left: 20,
    bottom: -50,
    width: 100,
    height: 100,
    backgroundColor: '#fff',
    borderRadius: 60,
    padding: 3,
    elevation: 3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profilePic: {
    width: '100%',
    height: '100%',
    borderRadius: 50,
  },
  profilePicPlaceholder: {
    width: '100%',
    height: '100%',
    borderRadius: 50,
    backgroundColor: '#2667ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  greetingContainer: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
  },
  greetingText: {
    color: '#fff',
    fontFamily: 'Outfit-Bold',
    fontSize: 16,
  },
  // Account Info
  accountInfo: {
    padding: 20,
    paddingTop: 60,
  },
  nameContainer: {
    marginBottom: 12,
  },
  accountName: {
    fontFamily: 'Outfit-Bold',
    fontSize: 24,
    color: '#000',
    marginBottom: 4,
  },
  accountUsername: {
    fontFamily: 'Outfit-Regular',
    fontSize: 16,
    color: '#666',
    marginBottom: 25,
  },
  bioContainer: {
    marginBottom: 16,
  },
  bioText: {
    fontFamily: 'Outfit-Regular',
    fontSize: 15,
    color: '#333',
    lineHeight: 22,
  },
  // Stats
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 20,
    paddingVertical: 15,
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
  },
  statItem: {
    alignItems: 'center',
  },
  statNumber: {
    fontFamily: 'Outfit-Bold',
    fontSize: 18,
    color: '#000',
    marginBottom: 4,
  },
  statLabel: {
    fontFamily: 'Outfit-Regular',
    fontSize: 14,
    color: '#666',
  },
  // Info Sections
  infoDivider: {
    height: 1,
    backgroundColor: '#eee',
    marginVertical: 20,
  },
  infoSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    backgroundColor: '#f9f9f9',
    padding: 12,
    borderRadius: 10,
  },
  infoIcon: {
    width: 24,
    marginRight: 15,
    textAlign: 'center',
    color: '#2667ff',
  },
  infoText: {
    fontFamily: 'Outfit-Regular',
    fontSize: 15,
    color: '#333',
    flex: 1,
  },
  // Buttons
  editProfileBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f0f4ff',
    padding: 12,
    borderRadius: 8,
    marginTop: 20,
    borderWidth: 1,
    borderColor: '#d6e0ff',
  },
  editProfileText: {
    fontFamily: 'Outfit-Bold',
    fontSize: 15,
    color: '#2667ff',
  },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 8,
    margin: 20,
    borderWidth: 1,
    borderColor: '#ffd6d6',
  },
  logoutText: {
    fontFamily: 'Outfit-Bold',
    fontSize: 15,
    color: '#ff3b30',
    marginLeft: 8,
  },
  // Navigation
  navLabelActive: {
    color: '#2667ff',
    fontWeight: 'bold',
  },
  // Other styles
  centerTab: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  tabTitle: {
    fontFamily: 'Outfit-Bold',
    fontSize: 22,
    color: '#2667ff',
  },
  accountTitle: {
    fontFamily: 'Outfit-Bold',
    fontSize: 20,
    color: '#2667ff',
    marginBottom: 18,
  },

  // Report Screen Styles
  reportHeader: {
    padding: 20,
    backgroundColor: '#f8f9fa',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  reportTitle: {
    fontFamily: 'Outfit-Bold',
    fontSize: 24,
    color: '#2667ff',
    marginBottom: 4,
  },
  reportSubtitle: {
    fontFamily: 'Outfit-Regular',
    fontSize: 16,
    color: '#666',
  },
  editWarning: {
    fontFamily: 'Outfit-Medium',
    fontSize: 13,
    color: '#ff9500',
    marginTop: 8,
    textAlign: 'center',
  },
  reportForm: {
    padding: 20,
  },
  inputGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    fontFamily: 'Outfit-Medium',
    fontSize: 16,
    color: '#333',
    marginBottom: 8,
  },
  reportInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    fontFamily: 'Outfit-Regular',
    backgroundColor: '#fff',
  },
  textArea: {
    height: 120,
    textAlignVertical: 'top',
  },
  suggestionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#e8f2ff',
    padding: 12,
    borderRadius: 8,
    marginBottom: 15,
  },
  suggestionText: {
    fontFamily: 'Outfit-Medium',
    fontSize: 14,
    color: '#2667ff',
    marginLeft: 8,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  categoryButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 20,
    backgroundColor: '#fff',
  },
  categoryButtonActive: {
    backgroundColor: '#2667ff',
    borderColor: '#2667ff',
  },
  categoryButtonText: {
    fontFamily: 'Outfit-Medium',
    fontSize: 14,
    color: '#666',
  },
  categoryButtonTextActive: {
    color: '#fff',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  locationInput: {
    flex: 1,
  },
  locationButton: {
    width: 50,
    height: 50,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  mediaRow: {
    flexDirection: 'row',
    gap: 15,
  },
  mediaButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    backgroundColor: '#fff',
  },
  mediaButtonText: {
    fontFamily: 'Outfit-Medium',
    fontSize: 14,
    color: '#2667ff',
    marginLeft: 8,
  },
  mediaPreview: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 10,
  },
  mediaImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
  },
  anonymousToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 30,
  },
  anonymousText: {
    fontFamily: 'Outfit-Medium',
    fontSize: 16,
    color: '#333',
    marginLeft: 10,
  },
  submitButton: {
    backgroundColor: '#2667ff',
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  submitButtonDisabled: {
    backgroundColor: '#ccc',
  },

  // Analytics Dashboard Styles
  dashboardContainer: {
    padding: 20,
  },
  dashboardTitle: {
    fontFamily: 'Outfit-Bold',
    fontSize: 24,
    color: '#2667ff',
    marginBottom: 20,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 15,
    marginBottom: 30,
  },
  statCard: {
    flex: 1,
    minWidth: 150,
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  statValue: {
    fontFamily: 'Outfit-Bold',
    fontSize: 28,
    color: '#2667ff',
    marginBottom: 5,
  },
  statTitle: {
    fontFamily: 'Outfit-Medium',
    fontSize: 14,
    color: '#666',
  },
  chartContainer: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 12,
    marginBottom: 20,
    elevation: 2,
  },
  chartTitle: {
    fontFamily: 'Outfit-Bold',
    fontSize: 18,
    color: '#333',
    marginBottom: 15,
  },
  noCategoriesContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
  },
  noCategoriesText: {
    fontFamily: 'Outfit-Regular',
    fontSize: 16,
    color: '#999',
    textAlign: 'center',
  },
  noReportsContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
  },
  noReportsText: {
    fontFamily: 'Outfit-Regular',
    fontSize: 16,
    color: '#999',
    textAlign: 'center',
  },

  // Report List Styles
  reportItem: {
    backgroundColor: '#fff',
    padding: 16,
    marginBottom: 10,
    borderRadius: 8,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  reportItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  reportItemTitle: {
    fontFamily: 'Outfit-Bold',
    fontSize: 16,
    color: '#333',
    flex: 1,
    marginRight: 10,
  },
  priorityBadge: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 12,
  },
  priorityText: {
    fontFamily: 'Outfit-Bold',
    fontSize: 12,
    color: '#fff',
  },
  reportItemDescription: {
    fontFamily: 'Outfit-Regular',
    fontSize: 14,
    color: '#666',
    marginBottom: 8,
  },
  reportItemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reportItemCategory: {
    fontFamily: 'Outfit-Medium',
    fontSize: 12,
    color: '#2667ff',
  },
  reportItemDate: {
    fontFamily: 'Outfit-Regular',
    fontSize: 12,
    color: '#999',
  },

  // Dashboard specific styles
  dashboardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  loadingText: {
    fontFamily: 'Outfit-Medium',
    fontSize: 16,
    color: '#666',
    marginTop: 10,
  },
  categoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  categoryName: {
    fontFamily: 'Outfit-Medium',
    fontSize: 14,
    color: '#333',
    width: 80,
  },
  categoryBar: {
    flex: 1,
    height: 8,
    backgroundColor: '#f0f0f0',
    borderRadius: 4,
    marginHorizontal: 10,
  },
  categoryBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  categoryCount: {
    fontFamily: 'Outfit-Bold',
    fontSize: 14,
    color: '#333',
    width: 30,
    textAlign: 'right',
  },
  recentReportItem: {
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    paddingBottom: 12,
    marginBottom: 12,
  },
  recentReportHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  recentReportTitle: {
    fontFamily: 'Outfit-Bold',
    fontSize: 14,
    color: '#333',
    flex: 1,
    marginRight: 10,
  },
  recentReportDescription: {
    fontFamily: 'Outfit-Regular',
    fontSize: 12,
    color: '#666',
    lineHeight: 16,
    marginBottom: 8,
  },
  recentReportFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  recentReportCategory: {
    fontFamily: 'Outfit-Medium',
    fontSize: 11,
    color: '#2667ff',
    backgroundColor: '#e8f2ff',
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 8,
  },
  recentReportStatus: {
    fontFamily: 'Outfit-Bold',
    fontSize: 11,
  },
  recentReportDate: {
    fontFamily: 'Outfit-Regular',
    fontSize: 11,
    color: '#999',
  },
  quickActions: {
    marginTop: 20,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 15,
  },
  actionButton: {
    flex: 1,
    minWidth: 150,
    backgroundColor: '#2667ff',
    padding: 20,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonText: {
    fontFamily: 'Outfit-Bold',
    fontSize: 14,
    color: '#fff',
    marginTop: 8,
  },

  // Back Navigation Styles
  backNavigation: {
    padding: 20,
    paddingBottom: 10,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },
  backButtonText: {
    fontFamily: 'Outfit-Medium',
    fontSize: 16,
    color: '#2667ff',
    marginLeft: 8,
  },

  // Chat Screen Styles
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  chatHeaderInfo: {
    flex: 1,
    marginLeft: 12,
  },
  chatHeaderTitle: {
    fontSize: 18,
    fontFamily: 'Outfit-Bold',
    color: '#333',
  },
  chatHeaderSubtitle: {
    fontSize: 12,
    fontFamily: 'Outfit-Regular',
    color: '#2667ff',
    marginTop: 2,
  },
  chatBotAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f0f4ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  chatMessagesContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  messageContainer: {
    marginBottom: 16,
  },
  messageBubble: {
    maxWidth: '80%',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
    marginBottom: 4,
  },
  botMessage: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff',
    borderBottomLeftRadius: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  userMessage: {
    alignSelf: 'flex-end',
    backgroundColor: '#2667ff',
    borderBottomRightRadius: 4,
  },
  messageText: {
    fontSize: 16,
    fontFamily: 'Outfit-Regular',
    lineHeight: 22,
  },
  botMessageText: {
    color: '#333',
  },
  userMessageText: {
    color: '#fff',
  },
  messageTime: {
    fontSize: 10,
    fontFamily: 'Outfit-Regular',
    marginTop: 4,
  },
  botMessageTime: {
    color: '#999',
  },
  userMessageTime: {
    color: '#cce7ff',
  },
  suggestionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
    marginLeft: 4,
  },
  suggestionChip: {
    backgroundColor: '#f0f4ff',
    borderWidth: 1,
    borderColor: '#2667ff',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginRight: 8,
    marginBottom: 6,
  },
  suggestionText: {
    fontSize: 12,
    fontFamily: 'Outfit-Medium',
    color: '#2667ff',
  },
  typingBubble: {
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  typingIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#999',
    marginRight: 4,
    opacity: 0.4,
  },
  chatInputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  chatInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    fontFamily: 'Outfit-Regular',
    maxHeight: 100,
    backgroundColor: '#f8f9fa',
  },
  sendButton: {
    marginLeft: 8,
    backgroundColor: '#2667ff',
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sendButtonDisabled: {
    backgroundColor: '#ccc',
  },

  // Role Selection Styles
  roleButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#ddd',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  roleButtonActive: {
    backgroundColor: '#2667ff',
    borderColor: '#2667ff',
  },
  roleButtonText: {
    fontFamily: 'Outfit-Bold',
    fontSize: 15,
    color: '#666',
  },
  roleButtonTextActive: {
    color: '#fff',
  },

  // Trophy/Gamification Styles
  trophyContainer: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 12,
    marginVertical: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  trophyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  trophyTitle: {
    fontFamily: 'Outfit-Bold',
    fontSize: 18,
    color: '#333',
    marginLeft: 10,
  },
  trophyGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 15,
  },
  trophyItem: {
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    minWidth: 100,
  },
  trophyItemUnlocked: {
    backgroundColor: '#fff3e0',
  },
  trophyIcon: {
    fontSize: 40,
    marginBottom: 8,
  },
  trophyIconLocked: {
    opacity: 0.3,
  },
  trophyName: {
    fontFamily: 'Outfit-Bold',
    fontSize: 12,
    color: '#333',
    textAlign: 'center',
    marginBottom: 4,
  },
  trophyDescription: {
    fontFamily: 'Outfit-Regular',
    fontSize: 10,
    color: '#666',
    textAlign: 'center',
  },
  trophyProgress: {
    fontFamily: 'Outfit-Medium',
    fontSize: 11,
    color: '#2667ff',
    marginTop: 4,
  },
  trophyBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: '#ff6b6b',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  trophyBadgeText: {
    fontFamily: 'Outfit-Bold',
    fontSize: 10,
    color: '#fff',
  },
  reportStatsCard: {
    backgroundColor: '#e8f2ff',
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reportStatsLeft: {
    flex: 1,
  },
  reportStatsTitle: {
    fontFamily: 'Outfit-Medium',
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
  },
  reportStatsValue: {
    fontFamily: 'Outfit-Bold',
    fontSize: 28,
    color: '#2667ff',
  },
  reportStatsIcon: {
    fontSize: 50,
  },

  // Test Feedback Styles
  feedbackContainer: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 20,
  },
  feedbackHeader: {
    marginBottom: 25,
  },
  feedbackTitle: {
    fontFamily: 'Outfit-Bold',
    fontSize: 24,
    color: '#2667ff',
    marginBottom: 8,
  },
  feedbackSubtitle: {
    fontFamily: 'Outfit-Regular',
    fontSize: 14,
    color: '#666',
  },
  feedbackSection: {
    marginBottom: 25,
  },
  feedbackLabel: {
    fontFamily: 'Outfit-Bold',
    fontSize: 16,
    color: '#333',
    marginBottom: 10,
  },
  timeRow: {
    flexDirection: 'row',
    gap: 10,
  },
  timeInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    fontFamily: 'Outfit-Regular',
    backgroundColor: '#f8f9fa',
  },
  feedbackTextArea: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    fontFamily: 'Outfit-Regular',
    backgroundColor: '#f8f9fa',
    height: 150,
    textAlignVertical: 'top',
  },
  submitFeedbackButton: {
    backgroundColor: '#000',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
  },
  submitFeedbackButtonText: {
    fontFamily: 'Outfit-Bold',
    fontSize: 16,
    color: '#fff',
  },
  feedbackPreview: {
    backgroundColor: '#f8f9fa',
    padding: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  feedbackPreviewTitle: {
    fontFamily: 'Outfit-Bold',
    fontSize: 14,
    color: '#333',
    marginBottom: 8,
  },
  feedbackPreviewText: {
    fontFamily: 'Outfit-Regular',
    fontSize: 12,
    color: '#666',
    lineHeight: 18,
  },
  testVersionBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: '#ff6b6b',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  testVersionText: {
    fontFamily: 'Outfit-Bold',
    fontSize: 12,
    color: '#fff',
  },
});
